-- MySQL Script generated by MySQL Workbench
-- Tue Mar  5 17:54:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema evl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema evl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `evl` DEFAULT CHARACTER SET utf8 ;
USE `evl` ;

-- -----------------------------------------------------
-- Table `evl`.`imported`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evl`.`imported` (
  `router` SMALLINT NOT NULL,
  `date` DATE NOT NULL,
  `id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`router`, `date`, `id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evl`.`time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evl`.`time` (
  `date` DATE NOT NULL,
  PRIMARY KEY (`date`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `evl`.`info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evl`.`info` (
  `idPrimaryKey` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `router` VARCHAR(4) NOT NULL,
  `datetime` DATETIME NOT NULL,
  `FW` VARCHAR(45) NOT NULL,
  `prio` TINYINT UNSIGNED NOT NULL,
  `id` INT UNSIGNED NOT NULL,
  `rev` TINYINT UNSIGNED NOT NULL,
  `event` VARCHAR(45) NOT NULL,
  `rule` VARCHAR(45) NOT NULL,
  `ipproto` VARCHAR(10) NULL,
  `ipdatalen` TINYINT UNSIGNED NULL,
  `srcport` SMALLINT UNSIGNED NULL,
  `destport` SMALLINT UNSIGNED NULL,
  `tcphdrlen` TINYINT UNSIGNED NULL,
  `syn` TINYINT UNSIGNED NULL,
  `ece` TINYINT UNSIGNED NULL,
  `cwr` TINYINT UNSIGNED NULL,
  `ttl` TINYINT UNSIGNED NULL,
  `ttlmin` TINYINT UNSIGNED NULL,
  `udptotlen` TINYINT UNSIGNED NULL,
  `ipaddr` VARCHAR(45) NULL,
  `iface` VARCHAR(45) NULL,
  `origsent` SMALLINT UNSIGNED NULL,
  `termsent` SMALLINT UNSIGNED NULL,
  `conntime` SMALLINT UNSIGNED NULL,
  `conn` VARCHAR(45) NULL,
  `action` VARCHAR(45) NULL,
  `badflag` VARCHAR(45) NULL,
  `recvif` VARCHAR(45) NULL,
  `srcip` VARCHAR(45) NULL,
  `destip` VARCHAR(45) NULL,
  `ipdf` TINYINT UNSIGNED NULL,
  `time_date` DATE NOT NULL,
  PRIMARY KEY (`idPrimaryKey`),
  INDEX `fk_info_time_idx` (`time_date` ASC),
  CONSTRAINT `fk_info_time`
    FOREIGN KEY (`time_date`)
    REFERENCES `evl`.`time` (`date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
